# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d261090fe58082b3530f3d9f664590a4ac759ecc418bf6ffb060480662d06eefa8d44f4e38ad65dc139e56e144eb8d705cbe96a0e16195cd9d89264572435eda

test:
  secret_key_base: cbe3983ebfee43ff7ea0b137f2e1e4aa0ac8b212e70c542f989f59ec1ffab2af6c7b8e0e8df2ea657e89621c4fe195f46f96af820d69e08ab39861e3e578dc8b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
